name: Build Flutter Android APK

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'flutter_ai_bot/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'flutter_ai_bot/**'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      working-directory: ./flutter_ai_bot
      run: flutter pub get
      
    - name: Run Flutter tests
      working-directory: ./flutter_ai_bot
      run: flutter test
      
    - name: Build APK (Debug)
      working-directory: ./flutter_ai_bot
      run: flutter build apk --debug
      
    - name: Build APK (Release)
      working-directory: ./flutter_ai_bot
      run: flutter build apk --release
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-ai-bot-debug-apk
        path: flutter_ai_bot/build/app/outputs/flutter-apk/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-ai-bot-release-apk
        path: flutter_ai_bot/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Create Release (on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Flutter AI Bot v${{ github.run_number }}
        files: |
          flutter_ai_bot/build/app/outputs/flutter-apk/app-release.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
