name: Generate Android Keystore Base64

on:
  workflow_dispatch:
    inputs:
      keystore_path:
        description: 'Path to keystore file (.jks). Default: flutter_ai_bot/android/app/upload-keystore.jks'
        required: false
        default: 'flutter_ai_bot/android/app/upload-keystore.jks'

jobs:
  generate-base64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify keystore file exists
        id: check
        run: |
          FILE="${{ github.event.inputs.keystore_path }}"
          if [ ! -f "$FILE" ]; then
            echo "❌ Keystore not found at: $FILE"
            echo "Ensure the file exists in the repo or upload it temporarily and re-run."
            exit 1
          fi
          echo "✅ Found keystore at: $FILE"

      - name: Generate single-line base64
        id: encode
        shell: bash
        run: |
          FILE="${{ github.event.inputs.keystore_path }}"
          # Generate a single-line base64 string (no wrapping)
          BASE64=$(base64 -w 0 "$FILE")
          echo "base64=$BASE64" >> $GITHUB_OUTPUT
          # Prepare files for artifacts and summary
          mkdir -p output
          echo "$BASE64" > output/ANDROID_KEYSTORE_BASE64.txt

      - name: Add to job summary
        run: |
          echo "## Android Keystore Base64" >> $GITHUB_STEP_SUMMARY
          echo "The single-line base64 for your keystore has been generated." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Copy the content from the artifact file and paste it into your GitHub Secret named \`ANDROID_KEYSTORE_BASE64\`." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> Security note: Do NOT commit keystores or base64 strings to git. Use GitHub Secrets." >> $GITHUB_STEP_SUMMARY

      - name: Upload base64 as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ANDROID_KEYSTORE_BASE64
          path: output/ANDROID_KEYSTORE_BASE64.txt
          retention-days: 1
